baseURL = 'https://nevalang.org/'
languageCode = 'en-us'
title = 'Neva Programming Language'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Documentation'
pageRef = '/docs'
weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
