baseURL = 'https://nevalang.org/'
languageCode = 'en-us'
title = 'Neva Programming Language'

[[menus.main]]
name = 'Docs'
url = '/docs'
weight = 10

[[menus.main]]
name = 'Blog'
url = '/blog'
weight = 20

[[menus.main]]
name = 'GitHub'
url = "https://github.com/nevalang/neva"
weight = 30

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"
