// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: api/proto/src.proto

package srcproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityKind int32

const (
	EntityKind_ENTITY_KIND_UNSPECIFIED EntityKind = 0
	EntityKind_ENTITY_KIND_CONST       EntityKind = 1
	EntityKind_ENTITY_KIND_TYPE_DEF    EntityKind = 2
	EntityKind_ENTITY_KIND_INTERFACE   EntityKind = 3
	EntityKind_ENTITY_KIND_COMPONENT   EntityKind = 4
)

// Enum value maps for EntityKind.
var (
	EntityKind_name = map[int32]string{
		0: "ENTITY_KIND_UNSPECIFIED",
		1: "ENTITY_KIND_CONST",
		2: "ENTITY_KIND_TYPE_DEF",
		3: "ENTITY_KIND_INTERFACE",
		4: "ENTITY_KIND_COMPONENT",
	}
	EntityKind_value = map[string]int32{
		"ENTITY_KIND_UNSPECIFIED": 0,
		"ENTITY_KIND_CONST":       1,
		"ENTITY_KIND_TYPE_DEF":    2,
		"ENTITY_KIND_INTERFACE":   3,
		"ENTITY_KIND_COMPONENT":   4,
	}
)

func (x EntityKind) Enum() *EntityKind {
	p := new(EntityKind)
	*p = x
	return p
}

func (x EntityKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityKind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_src_proto_enumTypes[0].Descriptor()
}

func (EntityKind) Type() protoreflect.EnumType {
	return &file_api_proto_src_proto_enumTypes[0]
}

func (x EntityKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityKind.Descriptor instead.
func (EntityKind) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_src_proto_rawDescGZIP(), []int{0}
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Imports  map[string]string  `protobuf:"bytes,1,rep,name=imports,proto3" json:"imports,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Entities map[string]*Entity `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_src_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_src_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_api_proto_src_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetImports() map[string]string {
	if x != nil {
		return x.Imports
	}
	return nil
}

func (x *File) GetEntities() map[string]*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type Entity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exported  bool       `protobuf:"varint,1,opt,name=exported,proto3" json:"exported,omitempty"`
	Kind      EntityKind `protobuf:"varint,2,opt,name=kind,proto3,enum=srcproto.EntityKind" json:"kind,omitempty"`
	Const     *Const     `protobuf:"bytes,3,opt,name=const,proto3" json:"const,omitempty"`
	TypeDef   *TypeDef   `protobuf:"bytes,4,opt,name=type_def,json=typeDef,proto3" json:"type_def,omitempty"`
	Interface *Interface `protobuf:"bytes,5,opt,name=interface,proto3" json:"interface,omitempty"`
	Component *Component `protobuf:"bytes,6,opt,name=component,proto3" json:"component,omitempty"`
}

func (x *Entity) Reset() {
	*x = Entity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_src_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_src_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_api_proto_src_proto_rawDescGZIP(), []int{1}
}

func (x *Entity) GetExported() bool {
	if x != nil {
		return x.Exported
	}
	return false
}

func (x *Entity) GetKind() EntityKind {
	if x != nil {
		return x.Kind
	}
	return EntityKind_ENTITY_KIND_UNSPECIFIED
}

func (x *Entity) GetConst() *Const {
	if x != nil {
		return x.Const
	}
	return nil
}

func (x *Entity) GetTypeDef() *TypeDef {
	if x != nil {
		return x.TypeDef
	}
	return nil
}

func (x *Entity) GetInterface() *Interface {
	if x != nil {
		return x.Interface
	}
	return nil
}

func (x *Entity) GetComponent() *Component {
	if x != nil {
		return x.Component
	}
	return nil
}

type Const struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ref   *EntityRef `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Value *Msg       `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Const) Reset() {
	*x = Const{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_src_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Const) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Const) ProtoMessage() {}

func (x *Const) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_src_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Const.ProtoReflect.Descriptor instead.
func (*Const) Descriptor() ([]byte, []int) {
	return file_api_proto_src_proto_rawDescGZIP(), []int{2}
}

func (x *Const) GetRef() *EntityRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *Const) GetValue() *Msg {
	if x != nil {
		return x.Value
	}
	return nil
}

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeExpr string          `protobuf:"bytes,1,opt,name=type_expr,json=typeExpr,proto3" json:"type_expr,omitempty"`
	Bool     bool            `protobuf:"varint,2,opt,name=bool,proto3" json:"bool,omitempty"`
	Int      int64           `protobuf:"varint,3,opt,name=int,proto3" json:"int,omitempty"`
	Float    float64         `protobuf:"fixed64,4,opt,name=float,proto3" json:"float,omitempty"`
	Str      string          `protobuf:"bytes,5,opt,name=str,proto3" json:"str,omitempty"`
	Vecs     []*Msg          `protobuf:"bytes,6,rep,name=vecs,proto3" json:"vecs,omitempty"`
	Map      map[string]*Msg `protobuf:"bytes,7,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_src_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_src_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_api_proto_src_proto_rawDescGZIP(), []int{3}
}

func (x *Msg) GetTypeExpr() string {
	if x != nil {
		return x.TypeExpr
	}
	return ""
}

func (x *Msg) GetBool() bool {
	if x != nil {
		return x.Bool
	}
	return false
}

func (x *Msg) GetInt() int64 {
	if x != nil {
		return x.Int
	}
	return 0
}

func (x *Msg) GetFloat() float64 {
	if x != nil {
		return x.Float
	}
	return 0
}

func (x *Msg) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

func (x *Msg) GetVecs() []*Msg {
	if x != nil {
		return x.Vecs
	}
	return nil
}

func (x *Msg) GetMap() map[string]*Msg {
	if x != nil {
		return x.Map
	}
	return nil
}

type TypeDef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params   []*TypeParam `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty"`
	BodyExpr string       `protobuf:"bytes,2,opt,name=body_expr,json=bodyExpr,proto3" json:"body_expr,omitempty"`
}

func (x *TypeDef) Reset() {
	*x = TypeDef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_src_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TypeDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeDef) ProtoMessage() {}

func (x *TypeDef) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_src_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeDef.ProtoReflect.Descriptor instead.
func (*TypeDef) Descriptor() ([]byte, []int) {
	return file_api_proto_src_proto_rawDescGZIP(), []int{4}
}

func (x *TypeDef) GetParams() []*TypeParam {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *TypeDef) GetBodyExpr() string {
	if x != nil {
		return x.BodyExpr
	}
	return ""
}

type Component struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Interface   *Interface       `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	Nodes       map[string]*Node `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Connections []*Connection    `protobuf:"bytes,3,rep,name=connections,proto3" json:"connections,omitempty"`
}

func (x *Component) Reset() {
	*x = Component{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_src_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Component) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Component) ProtoMessage() {}

func (x *Component) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_src_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Component.ProtoReflect.Descriptor instead.
func (*Component) Descriptor() ([]byte, []int) {
	return file_api_proto_src_proto_rawDescGZIP(), []int{5}
}

func (x *Component) GetInterface() *Interface {
	if x != nil {
		return x.Interface
	}
	return nil
}

func (x *Component) GetNodes() map[string]*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Component) GetConnections() []*Connection {
	if x != nil {
		return x.Connections
	}
	return nil
}

type Interface struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeParams []*TypeParam `protobuf:"bytes,1,rep,name=type_params,json=typeParams,proto3" json:"type_params,omitempty"`
	Io         *IO          `protobuf:"bytes,2,opt,name=io,proto3" json:"io,omitempty"`
}

func (x *Interface) Reset() {
	*x = Interface{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_src_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Interface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface) ProtoMessage() {}

func (x *Interface) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_src_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interface.ProtoReflect.Descriptor instead.
func (*Interface) Descriptor() ([]byte, []int) {
	return file_api_proto_src_proto_rawDescGZIP(), []int{6}
}

func (x *Interface) GetTypeParams() []*TypeParam {
	if x != nil {
		return x.TypeParams
	}
	return nil
}

func (x *Interface) GetIo() *IO {
	if x != nil {
		return x.Io
	}
	return nil
}

type TypeParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Constr string `protobuf:"bytes,2,opt,name=constr,proto3" json:"constr,omitempty"`
}

func (x *TypeParam) Reset() {
	*x = TypeParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_src_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TypeParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeParam) ProtoMessage() {}

func (x *TypeParam) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_src_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeParam.ProtoReflect.Descriptor instead.
func (*TypeParam) Descriptor() ([]byte, []int) {
	return file_api_proto_src_proto_rawDescGZIP(), []int{7}
}

func (x *TypeParam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TypeParam) GetConstr() string {
	if x != nil {
		return x.Constr
	}
	return ""
}

type IO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ins  []*Port `protobuf:"bytes,1,rep,name=ins,proto3" json:"ins,omitempty"`
	Outs []*Port `protobuf:"bytes,2,rep,name=outs,proto3" json:"outs,omitempty"`
}

func (x *IO) Reset() {
	*x = IO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_src_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IO) ProtoMessage() {}

func (x *IO) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_src_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IO.ProtoReflect.Descriptor instead.
func (*IO) Descriptor() ([]byte, []int) {
	return file_api_proto_src_proto_rawDescGZIP(), []int{8}
}

func (x *IO) GetIns() []*Port {
	if x != nil {
		return x.Ins
	}
	return nil
}

func (x *IO) GetOuts() []*Port {
	if x != nil {
		return x.Outs
	}
	return nil
}

type Port struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeExpr string `protobuf:"bytes,1,opt,name=type_expr,json=typeExpr,proto3" json:"type_expr,omitempty"`
	IsArray  bool   `protobuf:"varint,2,opt,name=is_array,json=isArray,proto3" json:"is_array,omitempty"`
}

func (x *Port) Reset() {
	*x = Port{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_src_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Port) ProtoMessage() {}

func (x *Port) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_src_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Port.ProtoReflect.Descriptor instead.
func (*Port) Descriptor() ([]byte, []int) {
	return file_api_proto_src_proto_rawDescGZIP(), []int{9}
}

func (x *Port) GetTypeExpr() string {
	if x != nil {
		return x.TypeExpr
	}
	return ""
}

func (x *Port) GetIsArray() bool {
	if x != nil {
		return x.IsArray
	}
	return false
}

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityRef    *EntityRef       `protobuf:"bytes,1,opt,name=entity_ref,json=entityRef,proto3" json:"entity_ref,omitempty"`
	TypeArgs     []string         `protobuf:"bytes,2,rep,name=type_args,json=typeArgs,proto3" json:"type_args,omitempty"`
	ComponentDis map[string]*Node `protobuf:"bytes,3,rep,name=component_dis,json=componentDis,proto3" json:"component_dis,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_src_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_src_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_api_proto_src_proto_rawDescGZIP(), []int{10}
}

func (x *Node) GetEntityRef() *EntityRef {
	if x != nil {
		return x.EntityRef
	}
	return nil
}

func (x *Node) GetTypeArgs() []string {
	if x != nil {
		return x.TypeArgs
	}
	return nil
}

func (x *Node) GetComponentDis() map[string]*Node {
	if x != nil {
		return x.ComponentDis
	}
	return nil
}

type EntityRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pkg  string `protobuf:"bytes,1,opt,name=pkg,proto3" json:"pkg,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *EntityRef) Reset() {
	*x = EntityRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_src_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityRef) ProtoMessage() {}

func (x *EntityRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_src_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityRef.ProtoReflect.Descriptor instead.
func (*EntityRef) Descriptor() ([]byte, []int) {
	return file_api_proto_src_proto_rawDescGZIP(), []int{11}
}

func (x *EntityRef) GetPkg() string {
	if x != nil {
		return x.Pkg
	}
	return ""
}

func (x *EntityRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Connection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderSide    *SenderConnectionSide     `protobuf:"bytes,1,opt,name=sender_side,json=senderSide,proto3" json:"sender_side,omitempty"`
	ReceiverSides []*ReceiverConnectionSide `protobuf:"bytes,2,rep,name=receiver_sides,json=receiverSides,proto3" json:"receiver_sides,omitempty"`
}

func (x *Connection) Reset() {
	*x = Connection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_src_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_src_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_api_proto_src_proto_rawDescGZIP(), []int{12}
}

func (x *Connection) GetSenderSide() *SenderConnectionSide {
	if x != nil {
		return x.SenderSide
	}
	return nil
}

func (x *Connection) GetReceiverSides() []*ReceiverConnectionSide {
	if x != nil {
		return x.ReceiverSides
	}
	return nil
}

type ReceiverConnectionSide struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PortAddr  *PortAddr `protobuf:"bytes,1,opt,name=port_addr,json=portAddr,proto3" json:"port_addr,omitempty"`
	Selectors []string  `protobuf:"bytes,2,rep,name=selectors,proto3" json:"selectors,omitempty"`
}

func (x *ReceiverConnectionSide) Reset() {
	*x = ReceiverConnectionSide{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_src_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiverConnectionSide) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiverConnectionSide) ProtoMessage() {}

func (x *ReceiverConnectionSide) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_src_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiverConnectionSide.ProtoReflect.Descriptor instead.
func (*ReceiverConnectionSide) Descriptor() ([]byte, []int) {
	return file_api_proto_src_proto_rawDescGZIP(), []int{13}
}

func (x *ReceiverConnectionSide) GetPortAddr() *PortAddr {
	if x != nil {
		return x.PortAddr
	}
	return nil
}

func (x *ReceiverConnectionSide) GetSelectors() []string {
	if x != nil {
		return x.Selectors
	}
	return nil
}

type SenderConnectionSide struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConstRef  *EntityRef `protobuf:"bytes,1,opt,name=const_ref,json=constRef,proto3" json:"const_ref,omitempty"`
	PortAddr  *PortAddr  `protobuf:"bytes,2,opt,name=port_addr,json=portAddr,proto3" json:"port_addr,omitempty"`
	Selectors []string   `protobuf:"bytes,3,rep,name=selectors,proto3" json:"selectors,omitempty"`
}

func (x *SenderConnectionSide) Reset() {
	*x = SenderConnectionSide{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_src_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SenderConnectionSide) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderConnectionSide) ProtoMessage() {}

func (x *SenderConnectionSide) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_src_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderConnectionSide.ProtoReflect.Descriptor instead.
func (*SenderConnectionSide) Descriptor() ([]byte, []int) {
	return file_api_proto_src_proto_rawDescGZIP(), []int{14}
}

func (x *SenderConnectionSide) GetConstRef() *EntityRef {
	if x != nil {
		return x.ConstRef
	}
	return nil
}

func (x *SenderConnectionSide) GetPortAddr() *PortAddr {
	if x != nil {
		return x.PortAddr
	}
	return nil
}

func (x *SenderConnectionSide) GetSelectors() []string {
	if x != nil {
		return x.Selectors
	}
	return nil
}

type PortAddr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node string `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Port string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	Idx  int32  `protobuf:"varint,3,opt,name=idx,proto3" json:"idx,omitempty"`
}

func (x *PortAddr) Reset() {
	*x = PortAddr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_src_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PortAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortAddr) ProtoMessage() {}

func (x *PortAddr) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_src_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortAddr.ProtoReflect.Descriptor instead.
func (*PortAddr) Descriptor() ([]byte, []int) {
	return file_api_proto_src_proto_rawDescGZIP(), []int{15}
}

func (x *PortAddr) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *PortAddr) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *PortAddr) GetIdx() int32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

var File_api_proto_src_proto protoreflect.FileDescriptor

var file_api_proto_src_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x72, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x82, 0x02, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x35, 0x0a, 0x07, 0x69, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x72, 0x63, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x12,
	0x38, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x72, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x49, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x4d, 0x0a, 0x0d, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x26, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x72, 0x63, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x89, 0x02, 0x0a, 0x06, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12,
	0x1a, 0x0a, 0x08, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x12, 0x28, 0x0a, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x73, 0x72, 0x63, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4b, 0x69, 0x6e, 0x64, 0x52,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x25, 0x0a, 0x05, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x72, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x6f, 0x6e, 0x73, 0x74, 0x52, 0x05, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x08,
	0x74, 0x79, 0x70, 0x65, 0x5f, 0x64, 0x65, 0x66, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x73, 0x72, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x44, 0x65,
	0x66, 0x52, 0x07, 0x74, 0x79, 0x70, 0x65, 0x44, 0x65, 0x66, 0x12, 0x31, 0x0a, 0x09, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x73, 0x72, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x52, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x31, 0x0a,
	0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x73, 0x72, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x70,
	0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x22, 0x53, 0x0a, 0x05, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x03, 0x72, 0x65, 0x66,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x72, 0x63, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x66, 0x52, 0x03, 0x72, 0x65, 0x66,
	0x12, 0x23, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x73, 0x72, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x84, 0x02, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x1b, 0x0a,
	0x09, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x65, 0x78, 0x70, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x79, 0x70, 0x65, 0x45, 0x78, 0x70, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f,
	0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x12, 0x10,
	0x0a, 0x03, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x69, 0x6e, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x74, 0x72, 0x12, 0x21, 0x0a, 0x04, 0x76, 0x65, 0x63, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x72, 0x63, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x04, 0x76, 0x65, 0x63, 0x73, 0x12, 0x28, 0x0a, 0x03, 0x6d,
	0x61, 0x70, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x72, 0x63, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x73, 0x67, 0x2e, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x03, 0x6d, 0x61, 0x70, 0x1a, 0x45, 0x0a, 0x08, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x72, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x73,
	0x67, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x53, 0x0a, 0x07,
	0x54, 0x79, 0x70, 0x65, 0x44, 0x65, 0x66, 0x12, 0x2b, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x72, 0x63, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x06, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6f, 0x64, 0x79, 0x5f, 0x65, 0x78, 0x70,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6f, 0x64, 0x79, 0x45, 0x78, 0x70,
	0x72, 0x22, 0xf6, 0x01, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x12,
	0x31, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x72, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x12, 0x34, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x72, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6d,
	0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x36, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x73, 0x72, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x1a, 0x48, 0x0a, 0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x24, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x73, 0x72, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x5f, 0x0a, 0x09, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x0b, 0x74, 0x79, 0x70, 0x65, 0x5f,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73,
	0x72, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x52, 0x0a, 0x74, 0x79, 0x70, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1c, 0x0a,
	0x02, 0x69, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x72, 0x63, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x4f, 0x52, 0x02, 0x69, 0x6f, 0x22, 0x37, 0x0a, 0x09, 0x54,
	0x79, 0x70, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f,
	0x6e, 0x73, 0x74, 0x72, 0x22, 0x4a, 0x0a, 0x02, 0x49, 0x4f, 0x12, 0x20, 0x0a, 0x03, 0x69, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x72, 0x63, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x03, 0x69, 0x6e, 0x73, 0x12, 0x22, 0x0a, 0x04,
	0x6f, 0x75, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x72, 0x63,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x04, 0x6f, 0x75, 0x74, 0x73,
	0x22, 0x3e, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x79, 0x70, 0x65,
	0x5f, 0x65, 0x78, 0x70, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x79, 0x70,
	0x65, 0x45, 0x78, 0x70, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x61, 0x72, 0x72, 0x61,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x41, 0x72, 0x72, 0x61, 0x79,
	0x22, 0xef, 0x01, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x32, 0x0a, 0x0a, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x73, 0x72, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x66, 0x52, 0x09, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x66, 0x12, 0x1b, 0x0a,
	0x09, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x79, 0x70, 0x65, 0x41, 0x72, 0x67, 0x73, 0x12, 0x45, 0x0a, 0x0d, 0x63, 0x6f,
	0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x69, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x73, 0x72, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64,
	0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x44, 0x69,
	0x73, 0x1a, 0x4f, 0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x44, 0x69,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x72, 0x63, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x31, 0x0a, 0x09, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x66, 0x12,
	0x10, 0x0a, 0x03, 0x70, 0x6b, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x6b,
	0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x96, 0x01, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3f, 0x0a, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x73,
	0x69, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x72, 0x63, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x64, 0x65, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x53, 0x69, 0x64, 0x65, 0x12, 0x47, 0x0a, 0x0e, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x72, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x73, 0x72, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x64, 0x65, 0x52,
	0x0d, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x53, 0x69, 0x64, 0x65, 0x73, 0x22, 0x67,
	0x0a, 0x16, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x64, 0x65, 0x12, 0x2f, 0x0a, 0x09, 0x70, 0x6f, 0x72, 0x74,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x72,
	0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x41, 0x64, 0x64, 0x72, 0x52,
	0x08, 0x70, 0x6f, 0x72, 0x74, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x97, 0x01, 0x0a, 0x14, 0x53, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x64, 0x65,
	0x12, 0x30, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x72, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x66, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x52,
	0x65, 0x66, 0x12, 0x2f, 0x0a, 0x09, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x72, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x50, 0x6f, 0x72, 0x74, 0x41, 0x64, 0x64, 0x72, 0x52, 0x08, 0x70, 0x6f, 0x72, 0x74, 0x41,
	0x64, 0x64, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x73, 0x22, 0x44, 0x0a, 0x08, 0x50, 0x6f, 0x72, 0x74, 0x41, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x78, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x69, 0x64, 0x78, 0x2a, 0x90, 0x01, 0x0a, 0x0a, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x1b, 0x0a, 0x17, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59,
	0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x5f, 0x4b, 0x49,
	0x4e, 0x44, 0x5f, 0x43, 0x4f, 0x4e, 0x53, 0x54, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x45, 0x4e,
	0x54, 0x49, 0x54, 0x59, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44,
	0x45, 0x46, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x5f, 0x4b,
	0x49, 0x4e, 0x44, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x46, 0x41, 0x43, 0x45, 0x10, 0x03, 0x12,
	0x19, 0x0a, 0x15, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x43,
	0x4f, 0x4d, 0x50, 0x4f, 0x4e, 0x45, 0x4e, 0x54, 0x10, 0x04, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x6b,
	0x67, 0x2f, 0x73, 0x72, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_proto_src_proto_rawDescOnce sync.Once
	file_api_proto_src_proto_rawDescData = file_api_proto_src_proto_rawDesc
)

func file_api_proto_src_proto_rawDescGZIP() []byte {
	file_api_proto_src_proto_rawDescOnce.Do(func() {
		file_api_proto_src_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_src_proto_rawDescData)
	})
	return file_api_proto_src_proto_rawDescData
}

var file_api_proto_src_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_src_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_proto_src_proto_goTypes = []interface{}{
	(EntityKind)(0),                // 0: srcproto.EntityKind
	(*File)(nil),                   // 1: srcproto.File
	(*Entity)(nil),                 // 2: srcproto.Entity
	(*Const)(nil),                  // 3: srcproto.Const
	(*Msg)(nil),                    // 4: srcproto.Msg
	(*TypeDef)(nil),                // 5: srcproto.TypeDef
	(*Component)(nil),              // 6: srcproto.Component
	(*Interface)(nil),              // 7: srcproto.Interface
	(*TypeParam)(nil),              // 8: srcproto.TypeParam
	(*IO)(nil),                     // 9: srcproto.IO
	(*Port)(nil),                   // 10: srcproto.Port
	(*Node)(nil),                   // 11: srcproto.Node
	(*EntityRef)(nil),              // 12: srcproto.EntityRef
	(*Connection)(nil),             // 13: srcproto.Connection
	(*ReceiverConnectionSide)(nil), // 14: srcproto.ReceiverConnectionSide
	(*SenderConnectionSide)(nil),   // 15: srcproto.SenderConnectionSide
	(*PortAddr)(nil),               // 16: srcproto.PortAddr
	nil,                            // 17: srcproto.File.ImportsEntry
	nil,                            // 18: srcproto.File.EntitiesEntry
	nil,                            // 19: srcproto.Msg.MapEntry
	nil,                            // 20: srcproto.Component.NodesEntry
	nil,                            // 21: srcproto.Node.ComponentDisEntry
}
var file_api_proto_src_proto_depIdxs = []int32{
	17, // 0: srcproto.File.imports:type_name -> srcproto.File.ImportsEntry
	18, // 1: srcproto.File.entities:type_name -> srcproto.File.EntitiesEntry
	0,  // 2: srcproto.Entity.kind:type_name -> srcproto.EntityKind
	3,  // 3: srcproto.Entity.const:type_name -> srcproto.Const
	5,  // 4: srcproto.Entity.type_def:type_name -> srcproto.TypeDef
	7,  // 5: srcproto.Entity.interface:type_name -> srcproto.Interface
	6,  // 6: srcproto.Entity.component:type_name -> srcproto.Component
	12, // 7: srcproto.Const.ref:type_name -> srcproto.EntityRef
	4,  // 8: srcproto.Const.value:type_name -> srcproto.Msg
	4,  // 9: srcproto.Msg.vecs:type_name -> srcproto.Msg
	19, // 10: srcproto.Msg.map:type_name -> srcproto.Msg.MapEntry
	8,  // 11: srcproto.TypeDef.params:type_name -> srcproto.TypeParam
	7,  // 12: srcproto.Component.interface:type_name -> srcproto.Interface
	20, // 13: srcproto.Component.nodes:type_name -> srcproto.Component.NodesEntry
	13, // 14: srcproto.Component.connections:type_name -> srcproto.Connection
	8,  // 15: srcproto.Interface.type_params:type_name -> srcproto.TypeParam
	9,  // 16: srcproto.Interface.io:type_name -> srcproto.IO
	10, // 17: srcproto.IO.ins:type_name -> srcproto.Port
	10, // 18: srcproto.IO.outs:type_name -> srcproto.Port
	12, // 19: srcproto.Node.entity_ref:type_name -> srcproto.EntityRef
	21, // 20: srcproto.Node.component_dis:type_name -> srcproto.Node.ComponentDisEntry
	15, // 21: srcproto.Connection.sender_side:type_name -> srcproto.SenderConnectionSide
	14, // 22: srcproto.Connection.receiver_sides:type_name -> srcproto.ReceiverConnectionSide
	16, // 23: srcproto.ReceiverConnectionSide.port_addr:type_name -> srcproto.PortAddr
	12, // 24: srcproto.SenderConnectionSide.const_ref:type_name -> srcproto.EntityRef
	16, // 25: srcproto.SenderConnectionSide.port_addr:type_name -> srcproto.PortAddr
	2,  // 26: srcproto.File.EntitiesEntry.value:type_name -> srcproto.Entity
	4,  // 27: srcproto.Msg.MapEntry.value:type_name -> srcproto.Msg
	11, // 28: srcproto.Component.NodesEntry.value:type_name -> srcproto.Node
	11, // 29: srcproto.Node.ComponentDisEntry.value:type_name -> srcproto.Node
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_api_proto_src_proto_init() }
func file_api_proto_src_proto_init() {
	if File_api_proto_src_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_src_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_src_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Entity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_src_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Const); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_src_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_src_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TypeDef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_src_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Component); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_src_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Interface); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_src_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TypeParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_src_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_src_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Port); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_src_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_src_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_src_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Connection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_src_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiverConnectionSide); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_src_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SenderConnectionSide); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_src_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PortAddr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_src_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_src_proto_goTypes,
		DependencyIndexes: file_api_proto_src_proto_depIdxs,
		EnumInfos:         file_api_proto_src_proto_enumTypes,
		MessageInfos:      file_api_proto_src_proto_msgTypes,
	}.Build()
	File_api_proto_src_proto = out.File
	file_api_proto_src_proto_rawDesc = nil
	file_api_proto_src_proto_goTypes = nil
	file_api_proto_src_proto_depIdxs = nil
}
