/*
 * API Title
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sdk

import (
	"context"
	"net/http"
	"errors"
)

// DefaultApiService is a service that implements the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// ProgramGet - 
func (s *DefaultApiService) ProgramGet(ctx context.Context, path string) (ImplResponse, error) {
	// TODO - update ProgramGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Program{}) or use other options such as http.Ok ...
	//return Response(200, Program{}), nil

	//TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	//return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ProgramGet method not implemented")
}

// ProgramPatch - 
func (s *DefaultApiService) ProgramPatch(ctx context.Context, path string, program Program) (ImplResponse, error) {
	// TODO - update ProgramPatch with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Program{}) or use other options such as http.Ok ...
	//return Response(200, Program{}), nil

	//TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	//return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ProgramPatch method not implemented")
}

// ProgramPost - 
func (s *DefaultApiService) ProgramPost(ctx context.Context, path string, program Program) (ImplResponse, error) {
	// TODO - update ProgramPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Program{}) or use other options such as http.Ok ...
	//return Response(200, Program{}), nil

	//TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	//return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ProgramPost method not implemented")
}
