/*
 * API Title
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sdk

//Implementation response defines an error code with the associated body
type ImplResponse struct {
	Code int
	Body interface{}
}
