/*
 * API Title
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sdk

type PortAddr struct {

	Node string `json:"node,omitempty"`

	Idx int32 `json:"idx,omitempty"`

	Port string `json:"port,omitempty"`
}

// AssertPortAddrRequired checks if the required fields are not zero-ed
func AssertPortAddrRequired(obj PortAddr) error {
	return nil
}

// AssertRecursePortAddrRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PortAddr (e.g. [][]PortAddr), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePortAddrRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPortAddr, ok := obj.(PortAddr)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPortAddrRequired(aPortAddr)
	})
}
