// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

type ComponentInput struct {
	Interface *InterfaceInput   `json:"interface"`
	Nodes     []*NodeInput      `json:"nodes"`
	Net       []ConnectionInput `json:"net"`
}

type ConnectionInput struct {
	SenderSide    *ReceiverConnectionSideInput `json:"senderSide"`
	ReceiverSides []SenderConnectionSideInput  `json:"receiverSides"`
}

type EntityRefInput struct {
	Pkg  string `json:"pkg"`
	Name string `json:"name"`
}

type IOInput struct {
	In  []*PortInput `json:"in"`
	Out []*PortInput `json:"out"`
}

type InterfaceInput struct {
	TypeParams []*TypeParamInput `json:"typeParams"`
	Io         *IOInput          `json:"io"`
}

type LocationInput struct {
	PkgName  string `json:"pkgName"`
	FileName string `json:"fileName"`
}

type NodeInput struct {
	EntityRef   *EntityRefInput `json:"entityRef"`
	TypeArgs    []*string       `json:"typeArgs"`
	ComponentDi []*NodeInput    `json:"componentDI"`
}

type PortAddrInput struct {
	Node string `json:"node"`
	Port int    `json:"port"`
	Idx  *int   `json:"idx,omitempty"`
}

type PortInput struct {
	TypeExpr *string `json:"typeExpr,omitempty"`
	IsArray  bool    `json:"isArray"`
}

type ReceiverConnectionSideInput struct {
	PortAddr  *PortAddrInput `json:"portAddr"`
	Selectors []*string      `json:"selectors"`
}

type SenderConnectionSideInput struct {
	ConstRef  *EntityRefInput `json:"constRef,omitempty"`
	PortAddr  *PortAddrInput  `json:"portAddr,omitempty"`
	Selectors []*string       `json:"selectors"`
}

type TypeParam struct {
	Name   string  `json:"name"`
	Constr *string `json:"constr,omitempty"`
}

type TypeParamInput struct {
	Name   string  `json:"name"`
	Constr *string `json:"constr,omitempty"`
}
