// Package parser implements source code parsing.
// It uses parser (and lexer) generated by ANTLR4 from neva.g4 grammar file.
package parser

import (
	"context"
	"fmt"

	"github.com/antlr4-go/antlr/v4"
	"golang.org/x/sync/errgroup"
	yaml "gopkg.in/yaml.v3"

	"github.com/nevalang/neva/internal/compiler"
	generated "github.com/nevalang/neva/internal/compiler/parser/generated"
	"github.com/nevalang/neva/internal/compiler/src"
)

type treeShapeListener struct {
	*generated.BasenevaListener
	file src.File
}

type Parser struct {
	isDebug bool
}

func (p Parser) ParseManifest(raw []byte) (src.Manifest, error) {
	var result src.Manifest
	if err := yaml.Unmarshal(raw, &result); err != nil {
		return src.Manifest{}, fmt.Errorf("yaml unmarshal: %w", err)
	}
	return result, nil
}

func (p Parser) ParsePackages(
	ctx context.Context,
	rawPackages map[string]compiler.RawPackage,
) (map[string]src.Package, error) {
	packages := make(map[string]src.Package, len(rawPackages))

	for pkgName, pkgFiles := range rawPackages {
		parsedFiles, err := p.ParseFiles(ctx, pkgFiles)
		if err != nil {
			return nil, fmt.Errorf("parse files: %w", err)
		}

		packages[pkgName] = parsedFiles
	}

	return packages, nil
}

func (p Parser) ParseFiles(ctx context.Context, files map[string][]byte) (map[string]src.File, error) {
	result := make(map[string]src.File, len(files))
	g, gctx := errgroup.WithContext(ctx)
	for name, bb := range files {
		name := name
		bb := bb
		g.Go(func() error {
			v, err := p.ParseFile(gctx, bb)
			if err != nil {
				return err
			}
			result[name] = v
			return nil
		})
	}
	if err := g.Wait(); err != nil {
		return nil, err
	}
	return result, nil
}

func (p Parser) ParseFile(ctx context.Context, bb []byte) (src.File, error) {
	input := antlr.NewInputStream(string(bb))
	lexer := generated.NewnevaLexer(input)
	stream := antlr.NewCommonTokenStream(lexer, 0)

	parse := generated.NewnevaParser(stream)
	if p.isDebug {
		parse.AddErrorListener(antlr.NewDiagnosticErrorListener(true))
	}
	parse.BuildParseTrees = true

	tree := parse.Prog()
	listener := &treeShapeListener{}

	antlr.ParseTreeWalkerDefault.Walk(listener, tree)

	return listener.file, nil
}

func MustNew(debug bool) Parser {
	return Parser{
		isDebug: debug,
	}
}
