// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DevServerClient is the client API for DevServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DevServerClient interface {
	ListPrograms(ctx context.Context, in *ListProgramsRequest, opts ...grpc.CallOption) (*ListProgramsResponse, error)
	GetProgram(ctx context.Context, in *GetProgramRequest, opts ...grpc.CallOption) (*GetProgramResponse, error)
	UpdateProgram(ctx context.Context, in *UpdateProgramRequest, opts ...grpc.CallOption) (*UpdateProgramResponse, error)
	StartDebugger(ctx context.Context, in *StartDebugRequest, opts ...grpc.CallOption) (DevServer_StartDebuggerClient, error)
	SendDebugMessage(ctx context.Context, in *DebugRequest, opts ...grpc.CallOption) (DevServer_SendDebugMessageClient, error)
}

type devServerClient struct {
	cc grpc.ClientConnInterface
}

func NewDevServerClient(cc grpc.ClientConnInterface) DevServerClient {
	return &devServerClient{cc}
}

func (c *devServerClient) ListPrograms(ctx context.Context, in *ListProgramsRequest, opts ...grpc.CallOption) (*ListProgramsResponse, error) {
	out := new(ListProgramsResponse)
	err := c.cc.Invoke(ctx, "/devserver.DevServer/ListPrograms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devServerClient) GetProgram(ctx context.Context, in *GetProgramRequest, opts ...grpc.CallOption) (*GetProgramResponse, error) {
	out := new(GetProgramResponse)
	err := c.cc.Invoke(ctx, "/devserver.DevServer/GetProgram", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devServerClient) UpdateProgram(ctx context.Context, in *UpdateProgramRequest, opts ...grpc.CallOption) (*UpdateProgramResponse, error) {
	out := new(UpdateProgramResponse)
	err := c.cc.Invoke(ctx, "/devserver.DevServer/UpdateProgram", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devServerClient) StartDebugger(ctx context.Context, in *StartDebugRequest, opts ...grpc.CallOption) (DevServer_StartDebuggerClient, error) {
	stream, err := c.cc.NewStream(ctx, &DevServer_ServiceDesc.Streams[0], "/devserver.DevServer/StartDebugger", opts...)
	if err != nil {
		return nil, err
	}
	x := &devServerStartDebuggerClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DevServer_StartDebuggerClient interface {
	Recv() (*StartDebugResponse, error)
	grpc.ClientStream
}

type devServerStartDebuggerClient struct {
	grpc.ClientStream
}

func (x *devServerStartDebuggerClient) Recv() (*StartDebugResponse, error) {
	m := new(StartDebugResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *devServerClient) SendDebugMessage(ctx context.Context, in *DebugRequest, opts ...grpc.CallOption) (DevServer_SendDebugMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &DevServer_ServiceDesc.Streams[1], "/devserver.DevServer/SendDebugMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &devServerSendDebugMessageClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DevServer_SendDebugMessageClient interface {
	Recv() (*DebugResponse, error)
	grpc.ClientStream
}

type devServerSendDebugMessageClient struct {
	grpc.ClientStream
}

func (x *devServerSendDebugMessageClient) Recv() (*DebugResponse, error) {
	m := new(DebugResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DevServerServer is the server API for DevServer service.
// All implementations must embed UnimplementedDevServerServer
// for forward compatibility
type DevServerServer interface {
	ListPrograms(context.Context, *ListProgramsRequest) (*ListProgramsResponse, error)
	GetProgram(context.Context, *GetProgramRequest) (*GetProgramResponse, error)
	UpdateProgram(context.Context, *UpdateProgramRequest) (*UpdateProgramResponse, error)
	StartDebugger(*StartDebugRequest, DevServer_StartDebuggerServer) error
	SendDebugMessage(*DebugRequest, DevServer_SendDebugMessageServer) error
	mustEmbedUnimplementedDevServerServer()
}

// UnimplementedDevServerServer must be embedded to have forward compatible implementations.
type UnimplementedDevServerServer struct {
}

func (UnimplementedDevServerServer) ListPrograms(context.Context, *ListProgramsRequest) (*ListProgramsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPrograms not implemented")
}
func (UnimplementedDevServerServer) GetProgram(context.Context, *GetProgramRequest) (*GetProgramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProgram not implemented")
}
func (UnimplementedDevServerServer) UpdateProgram(context.Context, *UpdateProgramRequest) (*UpdateProgramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProgram not implemented")
}
func (UnimplementedDevServerServer) StartDebugger(*StartDebugRequest, DevServer_StartDebuggerServer) error {
	return status.Errorf(codes.Unimplemented, "method StartDebugger not implemented")
}
func (UnimplementedDevServerServer) SendDebugMessage(*DebugRequest, DevServer_SendDebugMessageServer) error {
	return status.Errorf(codes.Unimplemented, "method SendDebugMessage not implemented")
}
func (UnimplementedDevServerServer) mustEmbedUnimplementedDevServerServer() {}

// UnsafeDevServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DevServerServer will
// result in compilation errors.
type UnsafeDevServerServer interface {
	mustEmbedUnimplementedDevServerServer()
}

func RegisterDevServerServer(s grpc.ServiceRegistrar, srv DevServerServer) {
	s.RegisterService(&DevServer_ServiceDesc, srv)
}

func _DevServer_ListPrograms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProgramsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevServerServer).ListPrograms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devserver.DevServer/ListPrograms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevServerServer).ListPrograms(ctx, req.(*ListProgramsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevServer_GetProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProgramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevServerServer).GetProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devserver.DevServer/GetProgram",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevServerServer).GetProgram(ctx, req.(*GetProgramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevServer_UpdateProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProgramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevServerServer).UpdateProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devserver.DevServer/UpdateProgram",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevServerServer).UpdateProgram(ctx, req.(*UpdateProgramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevServer_StartDebugger_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartDebugRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DevServerServer).StartDebugger(m, &devServerStartDebuggerServer{stream})
}

type DevServer_StartDebuggerServer interface {
	Send(*StartDebugResponse) error
	grpc.ServerStream
}

type devServerStartDebuggerServer struct {
	grpc.ServerStream
}

func (x *devServerStartDebuggerServer) Send(m *StartDebugResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _DevServer_SendDebugMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DebugRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DevServerServer).SendDebugMessage(m, &devServerSendDebugMessageServer{stream})
}

type DevServer_SendDebugMessageServer interface {
	Send(*DebugResponse) error
	grpc.ServerStream
}

type devServerSendDebugMessageServer struct {
	grpc.ServerStream
}

func (x *devServerSendDebugMessageServer) Send(m *DebugResponse) error {
	return x.ServerStream.SendMsg(m)
}

// DevServer_ServiceDesc is the grpc.ServiceDesc for DevServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DevServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devserver.DevServer",
	HandlerType: (*DevServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPrograms",
			Handler:    _DevServer_ListPrograms_Handler,
		},
		{
			MethodName: "GetProgram",
			Handler:    _DevServer_GetProgram_Handler,
		},
		{
			MethodName: "UpdateProgram",
			Handler:    _DevServer_UpdateProgram_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartDebugger",
			Handler:       _DevServer_StartDebugger_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendDebugMessage",
			Handler:       _DevServer_SendDebugMessage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "devserver.proto",
}
