name: lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  gofix_check:
    name: gofix-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26.1'
          cache: false
      - name: gofix-check
        run: |
          go fix ./...
          git diff --exit-code

  golangci:
    name: golangci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26.1'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          only-new-issues: true
          args: --config=.golangci.yml

  govulncheck:
    name: govulncheck
    runs-on: ubuntu-latest
    steps:
      - uses: golang/govulncheck-action@v1
        with:
          go-version-file: go.mod
          output-format: text
