/**
 * API Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Connection } from './Connection';
import { IO } from './IO';
import { HttpFile } from '../http/http';

export class Module {
    'io'?: IO;
    'workers'?: { [key: string]: string; };
    'deps'?: { [key: string]: IO; };
    'het'?: Array<Connection>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "io",
            "baseName": "io",
            "type": "IO",
            "format": ""
        },
        {
            "name": "workers",
            "baseName": "workers",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "deps",
            "baseName": "deps",
            "type": "{ [key: string]: IO; }",
            "format": ""
        },
        {
            "name": "het",
            "baseName": "het",
            "type": "Array<Connection>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Module.attributeTypeMap;
    }

    public constructor() {
    }
}

