/**
 * API Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PortAddr {
    'node'?: string;
    'idx'?: number;
    'port'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "node",
            "baseName": "node",
            "type": "string",
            "format": ""
        },
        {
            "name": "idx",
            "baseName": "idx",
            "type": "number",
            "format": ""
        },
        {
            "name": "port",
            "baseName": "port",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PortAddr.attributeTypeMap;
    }

    public constructor() {
    }
}

